# fly.toml app configuration file generated for restaurantappmern on 2023-10-17T09:24:34+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "restaurantappmern"
primary_region = "mad"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
